BEGIN;


CREATE TABLE IF NOT EXISTS public.services
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description character varying(100) COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    duration integer NOT NULL,
    medspa_id bigint NOT NULL,
    CONSTRAINT services_pkey PRIMARY KEY (id),
    CONSTRAINT unique_medspa_services UNIQUE (name, medspa_id)
);

CREATE TABLE IF NOT EXISTS public.medspas
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(13) COLLATE pg_catalog."default" NOT NULL,
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT medspas_pkey PRIMARY KEY (id),
    CONSTRAINT medspas_email_c081c349_uniq UNIQUE (email),
    CONSTRAINT medspas_phone_number_6b87c61f_uniq UNIQUE (phone_number)
);

CREATE TABLE IF NOT EXISTS public.appointments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    start_date date NOT NULL,
    start_time time without time zone NOT NULL,
    total_duration integer NOT NULL,
    total_price integer NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    medspa_id bigint NOT NULL,
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.appointment_services
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    appointment_id bigint NOT NULL,
    service_id bigint NOT NULL,
    CONSTRAINT appointment_services_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.services
    ADD CONSTRAINT services_medspa_id_28611431_fk_medspas_id FOREIGN KEY (medspa_id)
    REFERENCES public.medspas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS services_medspa_id_28611431
    ON public.services(medspa_id);


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_medspa_id_19539667_fk_medspas_id FOREIGN KEY (medspa_id)
    REFERENCES public.medspas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS appointments_med_spa_id_2f5897e9
    ON public.appointments(medspa_id);


ALTER TABLE IF EXISTS public.appointment_services
    ADD CONSTRAINT appointment_services_appointment_id_40b96890_fk_appointments_id FOREIGN KEY (appointment_id)
    REFERENCES public.appointments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS appointment_services_appointment_id_40b96890
    ON public.appointment_services(appointment_id);


ALTER TABLE IF EXISTS public.appointment_services
    ADD CONSTRAINT appointment_services_service_id_cf930aa0_fk_services_id FOREIGN KEY (service_id)
    REFERENCES public.services (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS appointment_services_service_id_cf930aa0
    ON public.appointment_services(service_id);

END;
