# Generated by Django 5.1 on 2024-08-29 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="med_spa",
            new_name="medspa",
        ),
    ]
