# Generated by Django 5.1 on 2024-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_rename_med_spa_appointment_medspa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="total_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
