# Generated by Django 5.1 on 2024-08-29 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medspa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("duration", models.IntegerField()),
                (
                    "medspa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="medspa.medspa"
                    ),
                ),
            ],
            options={
                "db_table": "services",
            },
        ),
    ]
