# Generated by Django 5.1 on 2024-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medspa", "0002_alter_medspa_email_alter_medspa_phone_number"),
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("name", "medspa_id"), name="unique_medspa_services"
            ),
        ),
    ]
