# Generated by Django 5.1 on 2024-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medspa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medspa",
            name="email",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="medspa",
            name="phone_number",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
